#!/bin/sh

if [ ! -n "$script_root" ]; then
  # Getting the hash to make sure that we're always pulling the latest. Do something better eventually.
  hash=$(curl https://api.github.com/repos/MynockSpit/wildflower/commits/master 2>/dev/null | grep sha | head -n1 | cut -d'"' -f4)
  script_root=https://raw.githubusercontent.com/MynockSpit/wildflower/$hash
fi

# The $DENO_INSTALL variable will be set if DENO has been installed correctly.
if [ ! -s "$DENO_INSTALL" ]; then
  # Deno require a manual step (adding to the PATH), so we can't do other commands until the user has done that. :/ 
  # I mean, we could try to guess at the deno install, but I'd rather not. At least for now
  echo "Deno not found! Attempting install..."

  curl -fsSL https://deno.land/install.sh | sh || {
    echo
    echo "No-permission install failed. Provide password for sudo install (or install it manually yourself.)"

    # Not sure we want this part?
    curl -fsSL https://deno.land/install.sh | sudo -u $USER sh || {
      echo
      echo "Could not install Deno."
      echo "Either re-run to try again, or install Deno manually:"
      echo "  https://docs.deno.com/runtime/manual/getting_started/installation"
      exit 1
    }
  }
fi

deno run --allow-read --allow-write --allow-env --allow-sys $script_root/wildflower.js "$@"