#!/bin/sh

if [ ! -n "$script_root" ]; then
  script_root=https://raw.githubusercontent.com/MynockSpit/wildflower/master
fi

# The $DENO_INSTALL variable will be set if DENO has been installed correctly.
if [ ! -s "$DENO_INSTALL" ]; then
  # Deno require a manual step (adding to the PATH), so we can't do other commands until the user has done that. :/ 
  # I mean, we could try to guess at the deno install, but I'd rather not. At least for now
  echo "Deno not found! Attempting install..."

  curl -fsSL https://deno.land/install.sh | sh || {
    echo
    echo "No-permission install failed. Provide password for sudo install (or install it manually yourself.)"

    # Not sure we want this part?
    curl -fsSL https://deno.land/install.sh | sudo -u $USER sh || {
      echo
      echo "Could not install Deno."
      echo "Either re-run to try again, or install Deno manually:"
      echo "  https://docs.deno.com/runtime/manual/getting_started/installation"
    }
  }
else
  deno run --allow-read --allow-write --allow-env $script_root/wildflower.js
fi
